### ISSUE TITLE
[!] The `react-native-payments` pod failed to validate due to 1 error:     - ERROR | attributes: Missing required attribute `summary`.

### ISSUE THREAD

**Issue by kushavi2509** [naoufal/react-native-payments#257]
Got this issue In version  
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-payments": "0.8.0",

**Comment by kushavi2509** [comment]
I had to downgrad to      **"react-native-payments": "0.7.1",**

**Comment by truongtq2506** [comment]
[!] The `react-native-payments` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.
Firstly, sr my english is not good. Might the solution here is not correct but at least time it'll help you.
"react-native-payments": "^0.8.1"
Path: node_modules/react-native-payments/react-native-payments.podspec\
s.summary          = pkg["description"] 
Missing it's mean can get the description in package.json.
Solution 1:    s.summary          = pkg["author"] 
Solution 2:   s.summary          = pkg["description"]  but add more one property "description": " describe something you want...."
Pod install again

**Comment by Odinwan** [comment]
> [!] The `react-native-payments` pod failed to validate due to 1 error:
> - ERROR | attributes: Missing required attribute `summary`.
> 
> Firstly, sr my english is not good. Might the solution here is not correct but at least time it'll help you.
> "react": "16.13.1",
> "react-native": "0.63.3",
> "react-native-payments": "^0.8.1"
> 
> Path: node_modules/react-native-payments/react-native-payments.podspec
> s.summary = pkg["description"]
> 
> Missing it's mean can get the string description in node_modules/react-native-payments/package.json.
> Solution 1: s.summary = pkg["author"]
> Solution 2: s.summary = pkg["description"] but add more one property "description": " describe something you
> want...."
> 
> Pod install again

work for me ty
